from app.core.defaults import (
    ASR_CONTEXT_WINDOW_SECONDS,
    EMBEDDING_DIMENSION,
    LOW_CONFIDENCE_THRESHOLD,
    REPRESENTATIVE_FRAMES_PER_SHOT,
    SEGMENT_TARGET_MAX_SECONDS,
    SEGMENT_TARGET_MIN_SECONDS,
    SEGMENT_TOP_K,
)


def test_defaults_are_positive() -> None:
    assert EMBEDDING_DIMENSION > 0
    assert ASR_CONTEXT_WINDOW_SECONDS > 0
    assert SEGMENT_TOP_K > 0
    assert SEGMENT_TARGET_MIN_SECONDS > 0
    assert SEGMENT_TARGET_MAX_SECONDS >= SEGMENT_TARGET_MIN_SECONDS
    assert REPRESENTATIVE_FRAMES_PER_SHOT == 2
    assert 0 < LOW_CONFIDENCE_THRESHOLD < 1
