from app.core.defaults import (
    ASR_CONTEXT_WINDOW_SECONDS,
    EMBEDDING_DIMENSION,
    FRAME_INDEX_INTERVAL_SECONDS,
    LOW_CONFIDENCE_THRESHOLD,
    REPRESENTATIVE_FRAMES_PER_SHOT,
    IMAGE_SEARCH_TOP_K,
    TEXT_SEARCH_TOP_K,
)


def test_defaults_are_positive() -> None:
    assert EMBEDDING_DIMENSION > 0
    assert ASR_CONTEXT_WINDOW_SECONDS > 0
    assert IMAGE_SEARCH_TOP_K > 0
    assert TEXT_SEARCH_TOP_K > 0
    assert FRAME_INDEX_INTERVAL_SECONDS > 0
    assert REPRESENTATIVE_FRAMES_PER_SHOT == 2
    assert 0 < LOW_CONFIDENCE_THRESHOLD < 1
