from __future__ import annotations

from pathlib import Path

APP_NAME = "Drama Finder"
APP_ENV = "development"
APP_HOST = "0.0.0.0"
APP_PORT = 8000

DATA_ROOT = Path("./data")
MANIFEST_ROOT = Path("./manifests")

EMBEDDING_DIMENSION = 3072
GEMINI_EMBEDDING_MODEL = "gemini-embedding-2-preview"

IMAGE_SEARCH_TOP_K = 10
TEXT_SEARCH_TOP_K = 20
FRAME_INDEX_INTERVAL_SECONDS = 3.0
ASR_CONTEXT_WINDOW_SECONDS = 5
ASR_MODEL_NAME = "small"
ASR_DEVICE = "auto"
ASR_COMPUTE_TYPE = "int8"
INGEST_SKIP_EMBEDDINGS = False
REPRESENTATIVE_FRAMES_PER_SHOT = 2
LOW_CONFIDENCE_THRESHOLD = 0.35
JOB_TIMEOUT_SECONDS = 7200
JOB_RETRY_COUNT = 1
